name: Update GitHub Activity
on:
  schedule:
      - cron: "30 * * * *"
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README Wwith latest GitHub activity
    runs-on: ubuntu-latest
  
    steps:
       - uses: actions/checkout@v2
       - uses: radouane-tamouss/github-activity-readme@master
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
